### ISSUE TITLE
Best approach to read out multiple registers simultaneously

### ISSUE THREAD

**Issue by denizs** [hirschenberger/modbus-rs#28]
Hey there,
I was just wondering whether there is any best practice approach on reading out multiple registers at once.

My current implementation comprises a vector of `ModbusRegister` structs, each comprising a field named `register`. I then iterate of this vector after 200 ms have passed since the most recent read out and call `read_holding_registers` on my client struct, passing in the appropriate register. As this strikes me as a pretty ugly implementation (while getting the job done), how you would handle this.

Reading in the range of numerically first and last register and then slicing the `Vec<u16>` in appropriate pieces seems somewhat cumbersome as well.

Best,
Deniz

**Comment by hirschenberger** [comment]
Hey Deniz,

I don't get the point. Do you mean, what would perform better? 

Do you have many registers that you want to read out that are scattered on a wide address range, so that you read much unnecessary data when you read the whole range with `read_holding_registers` at once? Then cherry-picking by only reading the required registers with one request each may be better.
As always, it depends on the network latency, the data size and layout and your hardware constraints.

I'd implement a background thread that constantly queries the whole range with one `read_holding_registers` and your `ModbusRegister` structs reference into that `Vec<u16>`.

**Comment by denizs** [comment]
Thanks for getting back to me Falco!
Yup, I was looking for your personal go-to approach :)
That said, it seems like the approaches I thought of pretty much line up with your considerations.

As to network latency and resources, I'm currently using a raspberry 3 and connect to our modbus server via Ethernet.

Cheers,
Deniz
